version: "3.8"

services:
  api:
    image: rhythm:latest
    command: uvicorn rhythm.api.main:app --host 0.0.0.0 --port 8000
    environment:
      - MLFLOW_HOST=mlflow
      - MLFLOW_PORT=5000
    ports:
      - 8000:8000

  mlflow:
    image: rhythm:latest
    command: mlflow server --host 0.0.0.0
    ports:
      - 3000:5000
